type Region = string;

const REGIONS_A: {[region: string]: number} = {
    "Nordenskiöld Land": 3003,
    "Finnmarkskysten": 3006,
    "Vest-Finnmark": 3007,
    "Nord-Troms": 3009,
    "Lyngen": 3010,
    "Tromsø": 3011,
    "Sør-Troms": 3012,
    "Indre Troms": 3013,
    "Lofoten og Vesterålen": 3014,
    "Ofoten": 3015,
    "Salten": 3016,
    "Svartisen": 3017,
    "Helgeland": 3018,
    "Trollheimen": 3022,
    "Romsdal": 3023,
    "Sunnmøre": 3024,
    "Indre Fjordane": 3027,
    "Jotunheimen": 3028,
    "Indre Sogn": 3029,
    "Voss": 3031,
    "Hallingdal": 3032,
    "Hardanger": 3034,
    "Vest-Telemark": 3035,
    "Heiane": 3037,
};
const REGIONS_B: {[region: string]: number} = {
    "Svalbard øst": 3001,
    "Svalbard vest": 3002,
    "Svalbard sør": 3004,
    "Øst-Finnmark": 3005,
    "Finnmarksvidda": 3008,
    "Nord-Trøndelag": 3019,
    "Sør-Trøndelag": 3020,
    "Ytre Nordmøre": 3021,
    "Nord-Gudbrandsdalen": 3025,
    "Ytre Fjordane": 3026,
    "Ytre Sogn": 3030,
    "Hordalandskysten": 3033,
    "Rogalandskysten": 3036,
    "Agder sør": 3038,
    "Telemark sør": 3039,
    "Vestfold": 3040,
    "Buskerud sør": 3041,
    "Oppland sør": 3042,
    "Hedmark": 3043,
    "Akershus": 3044,
    "Oslo": 3045,
    "Østfold":3046,
};
const REGIONS_C: {[region: string]: number} = {"No region": 4000};
const REGIONS_LAND = [
    "Agder",
    "Innlandet",
    "Møre og Romsdal",
    "Nordland",
    "Oslo",
    "Rogaland",
    "Troms og Finnmark",
    "Trøndelag",
    "Vestfold og Telemark",
    "Vestland",
    "Viken",
];
const REGIONS_WATER = [
    "Haldenvassdraget",
    "Glommavassdraget",
    "Mossevassdraget",
    "Hølenelva",
    "Nesodden og Bunnefjorden",
    "Nordmarkvassdraget",
    "Lysakerelva",
    "Sandvikelva",
    "Årosvassdraget",
    "Drammensvassdraget",
    "Numedalslågen og Siljansvassdraget",
    "Skiensvassdraget",
    "Vegårsvassdraget",
    "Arendalsvassdraget",
    "Otra",
    "Mandalselva",
    "Bjerkreimvassdraget",
    "Figgjo",
    "Saudavassdraget",
    "Vikedalselva",
    "Etnevassdraget",
    "Blåelva",
    "Stordøya",
    "Opo",
    "Tysso",
    "Eidfjordvassdraget, Kinso og Sima",
    "Granvinfjorden og Samlafjorden nord",
    "Sævareidelva",
    "Bergen og omegn",
    "Bergsdalsvassdraget",
    "Vossovassdraget",
    "Masfjorden",
    "Ytre Sognefjorden sør: Rutledal-Varmråk",
    "Viksvassdraget",
    "Nærøyelvi",
    "Aurlandsvassdraget",
    "Lærdalsvassdraget",
    "Årdalsvassdraget",
    "Fortunvassdraget",
    "Jostedøla",
    "Årøyvassdraget",
    "Høyangervassdraget",
    "Gaularvassdraget",
    "Jølstra",
    "Oselvvassdraget",
    "Gjengedalsvassdraget",
    "Breimsvassdraget",
    "Strynvassdraget",
    "Hornindalvassdraget",
    "Rovdefjorden sør og Syvdefjorden",
    "Ørstavassdraget",
    "Hareidlandet og Gurskøya",
    "Storfjorden sør, Sunnylvsfjorden og Geirangerfjord",
    "Rauma",
    "Eira",
    "Gusjåvassdraget",
    "Frænfjorden, Julsundet og Hustadvika",
    "Driva",
    "Kyst Tingvollfjorden-Surnadalsfjorden",
    "Surna",
    "Trondheimsleia øst: Stamnes-Agdenes fyr",
    "Orkla",
    "Gaula",
    "Nidelvvassdraget",
    "Stjørdalsvassdraget",
    "Verdalsvassdraget",
    "Snåsavassdraget",
    "Follavassdraget",
    "Trondheimsfjorden vest",
    "Osen og Flatanger kommuner",
    "Årgårdsvassdraget og Bogna",
    "Namsen",
    "Vefsna",
    "Leirfjord kommune",
    "Rossåga",
    "Ranavassdraget",
    "Fykanåga",
    "Beiarelva, Morsdalsfjorden og Nordfjorden",
    "Kyst Saltstraumen-Bodø-Tårnvikfjellet",
    "Skjomavassdraget",
    "Indre Ofotfjorden",
    "Østre Hinnøya",
    "Vestre Hinnøya",
    "Flakstadøya og Moskenesøya",
    "Gratangen og Lavangen",
    "Salangselva",
    "Lakselva og Lyselvvassdraget",
    "Målselvvassdraget",
    "Kvaløya og Tromsøya",
    "Tromsøysundet og Grøtsundet øst",
    "Ringvassøya",
    "Lakselva",
    "Signaldalselva",
    "Reisavassdraget",
    "Kvænangsvassdraget",
    "Altavassdraget",
    "Kvaløya",
    "Magerøya",
    "Lakselvvassdraget",
    "Tana",
    "Vestre Jakobselva",
]
const REGIONS_ICE = [
    "Agder",
    "Innlandet",
    "Møre og Romsdal",
    "Nordland",
    "Oslo",
    "Rogaland",
    "Troms og Finnmark",
    "Trøndelag",
    "Vestfold og Telemark",
    "Vestland",
    "Viken",
];
const REGIONS: {[region: string]: number} = {
    ...REGIONS_C,
    ...REGIONS_A,
    ...REGIONS_B,
}

export {REGIONS, REGIONS_A, REGIONS_B, REGIONS_C, REGIONS_LAND, REGIONS_WATER, REGIONS_ICE, Region};